### ISSUE TITLE
不知道可以不可以写个拖尸的脚本

### ISSUE THREAD

**Issue by wosafety0** [eeorunix/girls-frontline-helper#2]
网站上大佬们有写 不过不是基于airtest的 不会改

**Comment by eeorunix** [comment]
@wosafety0 拖尸是啥，已经跟不上术语了，描述一下我去写

**Comment by wosafety0** [comment]
> @wosafety0 拖尸是啥，已经跟不上术语了，描述一下我去写

https://github.com/LukeZhang0/Auto_GirlsFrontline 大佬看看这个 能把里面的脚本改成airtest的嘛

**Comment by eeorunix** [comment]
> > @wosafety0 拖尸是啥，已经跟不上术语了，描述一下我去写
> 
> https://github.com/LukeZhang0/Auto_GirlsFrontline 大佬看看这个 能把里面的脚本改成airtest的嘛

0-1和0-2拖尸已写，13-4诚然还没开图，慢慢更新。活动有打捞图也可以喊我写
